server:
  port: 80

eureka:
  instance:
    preferIpAddress: false
  client:
    registerWithEureka : true
    fetchRegistry : true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}


zuul:
  # Remove authorization headers from sensitive headers (set by default)
  sensitive-headers: Cookie,Set-Cookie
  #Service will be mapped under the /api URI
  #prefix: /api
#  Uncomment to disable auto-registering all services read from Eureka
#  ignoredServices: '*'
  ribbon:
    eager-load:
      enabled: true
      clients : tweet-service,user-servicee

spring:
  application:
    name: api-gateway

# Increase timeout to prevent hystrix error on first call
ribbon:
  eager-load:
    enabled: true
  ReadTimeout: 5000
  clients : tweet-service,user-service
  ConnectTimeout: 5000