server:
  port: 8600

eureka:
  instance:
    preferIpAddress: false
  client:
    registerWithEureka : true
    fetchRegistry : true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

spring:
  application:
    name: user-service
