server:
  port: 8500

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka : true
    fetchRegistry : true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

spring:
  application:
    name: tweet-service